In [1]:
import numpy as np

In [7]:
import pandas

In [10]:
a = [i for i in range(10)]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
b = np.array(a)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
c = np.array([i for i in range (5)])
c

array([0, 1, 2, 3, 4])

In [18]:
type(c)

numpy.ndarray

In [21]:
c = np.array(a, dtype = float)
c

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
c[2]

2.0

In [23]:
c = np.array(a, dtype = int)

In [24]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
c = np.array(a, dtype = float)

In [26]:
c

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:
b = [0., 1., 2., 3., 4., 5., 6.1, 7.2, 8.3, 9.5]

In [29]:
b = np.array(a, dtype = int)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
b = np.array(a, dtype = float)
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
c = ['sss', 1, 2, 3, 8, 9]
b = np.array(c)
b

array(['sss', '1', '2', '3', '8', '9'], dtype='<U11')

In [34]:
type(c)

list

In [42]:
print(b.shape)
print(b.size)


(6,)
6


In [49]:
c= np.array([[1,2,3,4],
             [3,4,5,6]])
print(c)
print(type(c))
print(c.size)
print(c.shape)


[[1 2 3 4]
 [3 4 5 6]]
<class 'numpy.ndarray'>
8
(2, 4)


In [52]:
c[1,3]

6